############## Admin ######################
############## LP ######################
lp_vault_azure_storage_secret: KFmEHf15wSKd474iiIFTlfiQuH3ZkrOKtDWSbbpJOAdWg/VJOi1yLjgnruBzdWmUu15FIRIokPwy4uMNl+BaSA==
lp_vault_graph_passport_key: # can be any random string; to check integrity of content submitted for reviewal
lp_vault_youtube_api_key:
lp_vault_dial_service_authorization:
