############## Common ######################

# Common vars for env
env: dev
proto: http
domain_name: sunbird-cloud.tekdi.net
ssh_public_key_deployer: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGrZGVHzGbYb6TtyXiyFo+/+cNLJvoe9DHMxh0QmOd40V6FKltk44cbXuqOmltAjM5iAMdoyZQ7sf5nPNi8Cw0OcKrc3j4VuSE3eVIMGVkiNL7mqGs3FxmF2eYsON87qaWWZcLocNDfwEgC+e+XUnQKSGzz4T4rjFUlIj88HsjdW3xLVq0yC/i3NS2LaCJjHhubnKFe6qElFc4pbD/CsQxFYSNUekk1/EUEXCIBMe1rdVb0hfNNl4SksUhcR/9N+TfILU0z4KmixiRg2zM8kXoixq1F5PbtvGhSC6boAVhD0SgebuwtuWH0XXMWYoex6sJl2yjSxN3ld9Y7CprWIKr ttpllt@vowellt1"
bootstrap_user: vaishali_k
bootstrap_key_path: /var/lib/jenkins/secrets/ops_ssh_key

#################### DP ##########################

# Is it same as `channel_data_exhaust_bucket`
secor_azure_container_name: sunbirdcloud
secor_alerts_slack_channel: ""

dp_azure_account_name: sunbirdcloud # azure storage account name
default_org_hash_id: "" # channel id of the organization

# Data products monitoring web hooks
data_exhaust_webhook_url: ""   ####Slack webhook
data_exhaust_Channel: ""      ### salck channel for data products alerts
data_exhaust_name:
bucket: sunbirdcloud  ####  same as secor_azure_container_name
stream_base_url: ""

# Media content
media_service_azure_tenant: "" # value have to be defined
media_service_azure_tenant: ""
media_service_azure_subscription_id: ""
media_service_azure_account_name: ""
media_service_azure_resource_group_name: ""
media_service_azure_token_client_key: ""
media_service_azure_token_client_secret: ""

# kafka topic required by core #
# Please do not change this #
ingestion_kafka_topics:
  - name: telemetry.ingestion
    num_of_partitions: 4
    replication_factor: 1
    retention_time: 604800000
