##########################################
# Starting Of Core VARS
env: dev                #Name of the environment, e.g. dev, staging or production.
env_name: "{{ env }}"
domain_name: sbcloud.tekdi.net           #Domain on which the portal will be accessed. e.g. staging.{implementation-name}.org
proto: http                 # Protocol
bootstrap_user: vaishali_k
bootstrap_key_path: /var/lib/jenkins/secrets/ops_ssh_key
ssh_public_key_deployer: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGrZGVHzGbYb6TtyXiyFo+/+cNLJvoe9DHMxh0QmOd40V6FKltk44cbXuqOmltAjM5iAMdoyZQ7sf5nPNi8Cw0OcKrc3j4VuSE3eVIMGVkiNL7mqGs3FxmF2eYsON87qaWWZcLocNDfwEgC+e+XUnQKSGzz4T4rjFUlIj88HsjdW3xLVq0yC/i3NS2LaCJjHhubnKFe6qElFc4pbD/CsQxFYSNUekk1/EUEXCIBMe1rdVb0hfNNl4SksUhcR/9N+TfILU0z4KmixiRg2zM8kXoixq1F5PbtvGhSC6boAVhD0SgebuwtuWH0XXMWYoex6sJl2yjSxN3ld9Y7CprWIKr ttpllt@vowellt1"             # SSH Public key for deployer user, with which ansible will execute tasks

ekstep_s3_env: dev                       # dev or qa of ekstep for plugins
learningservice_ip: 10.160.0.8                   # Load balancer IP for learning server
searchservice_ip: 10.160.0.8                    # search service Load balancer IP
analyticsapi_ip: 10.140.0.2                      # Analytics Service Load Balancer IP
keycloak_url: http://10.128.0.7:8080                    # Keycloak Load balancer IP; eg http://10.10.10.10
sunbird_default_channel: sunbird              # Organization channel name which portal will connect to
sunbird_app_name: Sunbird                       # By default app name will be sunbird
azure_account_name: sunbirdcloud                   # Storage account name for blobs
sunbird_content_azure_storage_container: sunbirdcloud # Conatainer store assets/public
swarm_load_balancer: 10.148.0.8  # Loadbalancer ip to push the logspout result to logstash in swarm

dp_azure_account_name: sunbirdcloud # azure storage account name
artifacts_container: 'artifacts'                  # Azure blob container name to save built artifacts

## Mail config
mail_server_host:
mail_server_username: ""
alerts_mailing_list : ""                # Comma separated mail list for Alerts; eg: user1@mail.com, user2@mail.com
sunbird_mail_server_from_email:         # Email ID that should be as from address in mails

# Kibana oauth authorized domains; for accessing kibana dashboard
kibana_oauth_authenticated_email_domains:
  - domain1
  - domain2
kibana_oauth_authenticated_email_ids:
  - email1
  - email2
monitor_alerts_mail_from_email:         # From Address for alert mails
sunbird_msg_sender:                     # SMS from Address; atleast 6 char
sunbird_android_app_url: ""             # Playstore url of android app; default is subird.org

# NOT MANDATORY VARS
keycloak_api_management_user_email: "admin@sunbird.org"
jenkins_url:                            # Jenkins urls to be accessed from slaves; eg "http://10.20.0.12:8080/jenkins"
sunbird_installation_email: "admin@sunbird.org" # fallback email for badger badge creation if the user doesn't have email address.
upstream_url: "{{azure_account_name}}.blob.core.windows.net/{{sunbird_content_azure_storage_container}}" # Proxy url to get /assets/public


####################### Please Check me #############################
## Not used
project: "sunbird"


################################################

# Keycloak values can be merged to keycloak role, once PR is merged
keycloak_build_src: "keycloak_build"
keycloak_ver: "keycloak-3.2.0.Final"
keycloak_sms_provider_build: "keycloak-email-phone-autthenticator-1.0-SNAPSHOT.jar"
keycloak_sms_provider_templates_src: "templates.tar.gz"
keycloak_sms_provider_templates_dest: "/opt/keycloak/themes/sunbird/login"
keycloak_ekstep_sunbird_login_theme_file: "login.tar.gz"
keycloak_ekstep_sunbird_login_theme_dest: "/opt/keycloak/themes/sunbird/login"
keycloak_postgresql: "postgresql-9.4.1212.jar"
sunbird_auth_version: 1.0v


