# !! Might deprecate
core_vault_sunbird_ekstep_api_key:
core_vault_sunbird_encryption_key:
core_vault_kong__test_jwt:

############# Core #######################
####### Secrets #######

core_vault_sunbird_trampoline_secret: abcd1234 # some 8 digit password for keycloak sso user
core_vault_postgres_password: abcd1234
core_vault_sunbird_azure_storage_key: KFmEHf15wSKd474iiIFTlfiQuH3ZkrOKtDWSbbpJOAdWg/VJOi1yLjgnruBzdWmUu15FIRIokPwy4uMNl+BaSA==
core_vault_docker_registry_url: "https://index.docker.io/v1" # use this value if using dockerhub
core_vault_docker_registry_user: vaishali007
core_vault_docker_registry_password: Vaishali@007
core_vault_proxy_site_key: |+

core_vault_proxy_site_crt: |+

core_vault_ansible_vault_password: 12345
################### DONT FILL THESE VARIABLES INITIALLY ###################

core_vault_sunbird_sso_publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAh3giDs/KL6qUyv3dSgeEy39R9xOSvb0tZ2mHA9rd6xB71m54E/3YIZeZr4PN2Uk6HG7o2NHAO7EaUg/yXu8jm6VmyXbpp9UFUq/Ug9az4Gu5OVQQ0xHDZqQun7h85Ehn7Qkx3nO6EdZ0sWmD+H3LUVpP8lkAfGeB+fXcFytAXHIspkpDoJl0PqGAn4nVJxGZrAvZqsjhzYxwQTJUmpudME+tgr1K8RjZgEQ7TeUHRE3PmXrttQgYJqY23IL3RIkPFJRurgwIpcMEOjbLfEd4QrytVk9feL/hnt+c6oXMpZYJlib76h2Yd0TJNuSMwGQtDLpPe2heLNi83LOl4pVR2wIDAQAB # Get After Keycloak Deployment
core_vault_sunbird_keycloak_user_federation_provider_id: 0c98bf66-4d9b-4477-93be-e7edd9529bb7

core_vault_sunbird_api_auth_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI1M2QzYjBkODFlYTg0Zjk4OTU1ZmE3NmFhODIzNjBhMiJ9.RPtAZKv4zY5nDi1LNXJgPKHl_5Pb7UhkQxzFsL_ry0w #Authorization key (JWT) to access Sunbird APIs. This will be in the output of deploy-apis.sh script, extracting it out is documented in the deployment wiki.
core_vault_sso_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjKa8CknM3tZxe7WTypD6YMLzh2WhUUkSQy0G1prgQfpHuYjI2ThByLJZafoqWBPTI5Q71z0jQj8sHXLtzHrTLd2rnD8+vncwb91w98gZR0CfvIak29mfHgdzCY1jbylCY5SS1WqotH9oJxSSLA5g2aD/bKW3PvRwoHeNlnbXM4G9880b3j2pCar1IQ2AMCJbfWxEMR6xkiVvn4woIjYRAxR7WGy51f9tnhFaumWgKDAhNtKzm1bGXyvbzMbwtwDkEm0efM9jT7hx+WdTrzp1425XHLPLFx4B4eS1ZsPjmljZ0Sv1O5QQ3IHdFiOqa1iNpzFaT5YcfGsFUUgyk1U/cwIDAQAB
######################## Not mandatory ###################################
core_vault_sunbird_fcm_account_key: ""
core_vault_sunbird_google_oauth_clientSecret:
core_vault_mail_server_password: ''
core_vault_keycloak_api_management_user_password: admin
core_vault_keystore_password: sunbird  #Password to use for encrypting cassandra keystore. Use a strong password.
vault_core_url_shortner_access_token: "" # Url shortner access token for learning-service; only if url_shortner enabled
core_vault_sunbird_sso_username: admin
core_vault_sunbird_sso_password: admin
core_vault_keycloak_password: "admin"
core_vault_grafana_admin_password: "sunbird"
core_vault_truststore_password: "sunbird" # Password for cassandra trust store
core_vault_trampoline_secret: "deep-secret" ## any 8 character value
core_vault_msg_91_auth_key:

# Portal one google sso
core_vault_sunbird_google_oauth_clientId_portal:
core_vault_sunbird_google_oauth_clientSecret_portal:
core_vault_sunbird_google_captcha_site_key_portal:
core_vault_sunbird_google_keycloak_secret:

# Oauth for logger kibana
core_vault_kibana_google_client_id:
core_vault_kibana_google_client_secret:
core_vault_kibana_cookie_secret: kibanaoauth # Cookie secret for kibana Oauth

####################### END OF VARS ##########################################

#NOT REQUIRED TO EDIT ##############################
core_vault_badger_admin_password: "sunbird"
core_vault_badging_authorization_key:
core_vault_jenkins_admin_username: "" #### if it is not required will remove
core_vault_jenkins_admin_password: "" #### if it is not required will remove
core_vault_proxy_prometheus_admin_creds: "admin"
core_vault_postgres_username: postgres  # dont change this value
core_vault_grafana_editor_password: "sunbird"
core_vault_grafana_dashboards_git_repo_url_with_credentails: "https://github.com/project-sunbird/grafana-dashboards.git"
core_vault_monitor_alerts_slack_url: ""
